### ISSUE TITLE
FileLoadException in AppServerBase.Setup()

### ISSUE THREAD

**Issue by Dagwaging** [kerryjiang/SuperWebSocket#20]
I receive the following exception when setting up a new WebSocketServer:

```ERROR - System.IO.FileLoadException: Could not load file or assembly 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'log4net, Version=1.2.11.0, Culture=neutral, PublicKeyToken=669e0ddf0bb1aa2a'
   at SuperSocket.SocketBase.Logging.Log4NetLogFactory..ctor(String log4netConfig)
   at SuperSocket.SocketBase.AppServerBase`2.Setup(IRootConfig rootConfig, IServerConfig config, ISocketServerFactory socketServerFactory, IReceiveFilterFactory`1 receiveFilterFactory, ILogFactory logFactory, IEnumerable`1 connectionFilters, IEnumerable`1 commandLoaders)
   at SuperSocket.SocketBase.AppServerBase`2.Setup(IServerConfig config, ISocketServerFactory socketServerFactory, IReceiveFilterFactory`1 receiveFilterFactory, ILogFactory logFactory, IEnumerable`1 connectionFilters, IEnumerable`1 commandLoaders)
   at SuperSocket.SocketBase.AppServerBase`2.Setup(Int32 port)```

This seems to be an issue with a version mismatch between the version of log4net specified in SuperSocket and the one specified in SuperWebSocket, and I think was due to a failure to update the project files when SuperSocket was updated to 1.6.4, but I have not yet found a fix.

**Comment by kerryjiang** [comment]
Cool, thanks for your contribution!
